// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest';
import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { SettingsView } from '../src/renderer/src/settings-view.jsx';

const state = (configured = false) => ({ keys: { OPENAI_API_KEY: configured }, settings: { maxItems: 1000, sheets: {} }, sheetRuns: [] });
const props = (configured = false) => ({ state: state(configured), meta: {}, onSaveKey: vi.fn(async () => true), onClearKey: vi.fn(async () => true), onTestImages: vi.fn(async () => ({ configured: true, model: 'fixture-image-model', accessVerified: true, generationVerified: false, message: 'The selected image model is available.' })) });
const draft = 'test-only-input'; // Deliberately not a real API credential.
afterEach(cleanup);

describe('image provider setup', () => {
  it('separates image API setup from writing and performs no automatic connection requests', () => {
    const handlers = props(); render(<SettingsView {...handlers} />);
    expect(screen.getByRole('heading', { name: 'Writing & research' })).toBeVisible();
    expect(screen.getByRole('heading', { name: 'Image generation' })).toBeVisible();
    expect(screen.getByLabelText('OpenAI API key')).toHaveAttribute('type', 'password');
    expect(screen.getByLabelText('OpenAI API key')).toHaveAttribute('autoComplete', 'off');
    expect(screen.getByText('Setup needed')).toBeVisible();
    expect(screen.getByRole('button', { name: 'Save image key' })).toBeDisabled();
    expect(screen.getByRole('button', { name: 'Check image access' })).toBeDisabled();
    expect(screen.getByText(/Desktop credentials are stored on this computer/)).toHaveTextContent('backend and never sent to browsers');
    expect(handlers.onTestImages).not.toHaveBeenCalled();
    expect(handlers.onSaveKey).not.toHaveBeenCalled();
  });
  it('sends only an explicit credential save and clears the password field after success', async () => {
    const handlers = props(); render(<SettingsView {...handlers} />);
    fireEvent.change(screen.getByLabelText('OpenAI API key'), { target: { value: draft } });
    fireEvent.click(screen.getByRole('button', { name: 'Save image key' }));
    await waitFor(() => expect(handlers.onSaveKey).toHaveBeenCalledWith('OPENAI_API_KEY', draft));
    await waitFor(() => expect(screen.getByLabelText('OpenAI API key')).toHaveValue(''));
    expect(handlers.onTestImages).not.toHaveBeenCalled();
  });
  it.each(['returned-failure', 'thrown-failure'])('keeps the local entry when a save fails: %s', async mode => {
    const handlers = props(); handlers.onSaveKey = mode === 'returned-failure' ? vi.fn(async () => null) : vi.fn(async () => { throw new Error('fixture storage failure'); });
    render(<SettingsView {...handlers} />);
    fireEvent.change(screen.getByLabelText('OpenAI API key'), { target: { value: draft } });
    fireEvent.click(screen.getByRole('button', { name: 'Save image key' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('Your entry is still here');
    expect(screen.getByLabelText('OpenAI API key')).toHaveValue(draft);
    expect(screen.getByRole('alert')).not.toHaveTextContent(draft);
    expect(handlers.onTestImages).not.toHaveBeenCalled();
  });
  it('shows credential presence separately from an explicit access check and never claims generation was verified', async () => {
    const handlers = props(true); render(<SettingsView {...handlers} />);
    expect(screen.getByText('Credential saved')).toBeVisible();
    expect(screen.queryByText('Image model access confirmed')).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: 'Check image access' }));
    expect(await screen.findByText('Image model access confirmed')).toBeVisible();
    expect(handlers.onTestImages).toHaveBeenCalledOnce();
    expect(handlers.onTestImages).toHaveBeenCalledWith();
    expect(screen.getByText('Model: fixture-image-model')).toBeVisible();
    expect(screen.getByText(/No image was generated by this check/)).toBeVisible();
    expect(screen.queryByText('Generation verified', { exact: true })).not.toBeInTheDocument();
  });
  it('shows unsuccessful access and connection errors as real receipts without discarding the credential', async () => {
    const handlers = props(true); handlers.onTestImages.mockResolvedValueOnce({ configured: true, accessVerified: false, generationVerified: false, message: 'Image access is not enabled for this project.' }).mockRejectedValueOnce(new Error('Connection unavailable.'));
    render(<SettingsView {...handlers} />);
    fireEvent.click(screen.getByRole('button', { name: 'Check image access' }));
    expect(await screen.findByText('Image access needs attention')).toBeVisible();
    expect(screen.getByText('Image access is not enabled for this project.')).toBeVisible();
    fireEvent.click(screen.getByRole('button', { name: 'Check image access' }));
    expect(await screen.findByRole('alert')).toHaveTextContent('Connection unavailable.');
    expect(screen.getByText('Credential saved')).toBeVisible();
    expect(handlers.onClearKey).not.toHaveBeenCalled();
  });
  it('removes credentials only through an explicit action and clears the previous access receipt', async () => {
    const handlers = props(true); render(<SettingsView {...handlers} />);
    fireEvent.click(screen.getByRole('button', { name: 'Check image access' }));
    await screen.findByText('Image model access confirmed');
    fireEvent.click(screen.getByRole('button', { name: 'Remove saved key' }));
    await waitFor(() => expect(handlers.onClearKey).toHaveBeenCalledWith('OPENAI_API_KEY'));
    await waitFor(() => expect(screen.queryByText('Image model access confirmed')).not.toBeInTheDocument());
  });
});
