const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('apifyStudio', {
  appMeta: () => ipcRenderer.invoke('app-meta'),
  state: () => ipcRenderer.invoke('state'),
  listMissions: () => ipcRenderer.invoke('list-missions'),
  saveMission: (payload) => ipcRenderer.invoke('save-mission', payload),
  runMission: (missionId) => ipcRenderer.invoke('run-mission', missionId),
  runActionGraph: (payload) => ipcRenderer.invoke('run-action-graph', payload),
  pauseMission: (missionId) => ipcRenderer.invoke('pause-mission', missionId),
  scheduleMission: (payload) => ipcRenderer.invoke('schedule-mission', payload),
  discoverApifyResource: (payload) => ipcRenderer.invoke('discover-apify-resource', payload),
  testRecipe: (payload) => ipcRenderer.invoke('test-recipe', payload),
  saveRecipeVersion: (payload) => ipcRenderer.invoke('save-recipe-version', payload),
  getJob: (jobId) => ipcRenderer.invoke('get-job', jobId),
  retryJob: (jobId) => ipcRenderer.invoke('retry-job', jobId),
  readJobLog: (jobId) => ipcRenderer.invoke('read-job-log', jobId),
  searchEvidence: (payload) => ipcRenderer.invoke('search-evidence', payload),
  readEvidence: (evidenceId) => ipcRenderer.invoke('read-evidence', evidenceId),
  exportMissionBundle: (missionId) => ipcRenderer.invoke('export-mission-bundle', missionId),
  exportAssetPack: (payload) => ipcRenderer.invoke('export-asset-pack', payload),
  checkCodex: () => ipcRenderer.invoke('check-codex'),
  planIntent: (payload) => ipcRenderer.invoke('plan-intent', payload),
  runIntent: (payload) => ipcRenderer.invoke('run-intent', payload),
  runIntentAction: (payload) => ipcRenderer.invoke('run-intent-action', payload),
  saveKey: (keyName, value) => ipcRenderer.invoke('save-key', { keyName, value }),
  clearKey: (keyName) => ipcRenderer.invoke('clear-key', keyName),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  saveCard: (card) => ipcRenderer.invoke('save-card', card),
  moveCard: (payload) => ipcRenderer.invoke('move-card', payload),
  saveAsset: (asset) => ipcRenderer.invoke('save-asset', asset),
  saveRecipe: (recipe) => ipcRenderer.invoke('save-recipe', recipe),
  deleteRecipe: (recipeId) => ipcRenderer.invoke('delete-recipe', recipeId),
  runRecipe: (recipeId) => ipcRenderer.invoke('run-recipe', recipeId),
  readDataset: (datasetId) => ipcRenderer.invoke('read-dataset', datasetId),
  exportDataset: (payload) => ipcRenderer.invoke('export-dataset', payload),
  testSheetsBridge: () => ipcRenderer.invoke('test-sheets-bridge'),
  archiveAndClearSheets: (payload) => ipcRenderer.invoke('archive-and-clear-sheets', payload),
  importWorkingSheets: () => ipcRenderer.invoke('import-working-sheets'),
  exportDatasetToSheets: (payload) => ipcRenderer.invoke('export-dataset-to-sheets', payload),
  replaySheetRun: (sheetRunId) => ipcRenderer.invoke('replay-sheet-run', sheetRunId),
  readAnalysis: (analysisId) => ipcRenderer.invoke('read-analysis', analysisId),
  analyzeDataset: (payload) => ipcRenderer.invoke('analyze-dataset', payload),
  openAnalysisOutput: (analysisId) => ipcRenderer.invoke('open-analysis-output', analysisId),
  revealAnalysisOutput: (analysisId) => ipcRenderer.invoke('reveal-analysis-output', analysisId),
  generateAssets: (payload) => ipcRenderer.invoke('generate-assets', payload),
  openDataFolder: () => ipcRenderer.invoke('open-data-folder'),
  openAssetsFolder: () => ipcRenderer.invoke('open-assets-folder'),
  openAsset: (assetId) => ipcRenderer.invoke('open-asset', assetId),
  revealAsset: (assetId) => ipcRenderer.invoke('reveal-asset', assetId),
  openWorkspace: (projectId) => ipcRenderer.invoke('open-workspace', projectId),
  cancelJob: (jobId) => ipcRenderer.invoke('cancel-job', jobId),
  onStateChanged: (callback) => {
    const listener = (_, payload) => callback(payload);
    ipcRenderer.on('state-changed', listener);
    return () => ipcRenderer.removeListener('state-changed', listener);
  },
});
