const { contextBridge, ipcRenderer } = require('electron');

// Electron wraps every main-process failure as "Error invoking remote method 'x': Error: …".
// People should only ever read the message itself.
const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args).catch((error) => {
  throw new Error(String(error?.message || error).replace(/^Error invoking remote method '[^']+':\s*/, '').replace(/^(?:[A-Za-z]*Error):\s*/, ''));
});

contextBridge.exposeInMainWorld('apifyStudio', {
  publishStudioRun: payload => invoke('studio:publishStudioRun', payload),
  contentCatalog: (payload) => invoke('studio:contentCatalog', payload),
  selectContentWorkspace: (payload) => invoke('studio:selectContentWorkspace', payload),
  saveContentWorkspace: (payload) => invoke('studio:saveContentWorkspace', payload),
  saveResearchProgram: (payload) => invoke('studio:saveResearchProgram', payload),
  startResearchRun: (payload) => invoke('studio:startResearchRun', payload),
  approveResearchThemes: (payload) => invoke('studio:approveResearchThemes', payload),
  decideResearchTheme: (payload) => invoke('studio:decideResearchTheme', payload),
  continueResearchRun: (payload) => invoke('studio:continueResearchRun', payload),
  createContentRun: (payload) => invoke('studio:createContentRun', payload),
  cancelStudioRun: (payload) => invoke('studio:cancelStudioRun', payload),
  retryStudioRun: (payload) => invoke('studio:retryStudioRun', payload),
  readStudioRun: (payload) => invoke('studio:readStudioRun', payload),
  exportStudioRun: (payload) => invoke('studio:exportStudioRun', payload),
  readStudioAsset: (payload) => invoke('studio:readStudioAsset', payload),
  openStudioAsset: (payload) => invoke('studio:openStudioAsset', payload),
  importStudioSource: (payload) => invoke('studio:importStudioSource', payload),
  saveWorkspaceTaxonomy: (payload) => invoke('studio:saveWorkspaceTaxonomy', payload),
  saveReferenceDoc: (payload) => invoke('studio:saveReferenceDoc', payload),
  readReferenceDoc: (payload) => invoke('studio:readReferenceDoc', payload),
  deleteReferenceDoc: (payload) => invoke('studio:deleteReferenceDoc', payload),
  // Ask AI: questions about the app, answered from the app guide and this person's setup.
  askHelp: (payload) => invoke('help:ask', payload),
  // Share a setup: export to a file, open one for preview, then import the previewed file.
  exportSetup: (payload) => invoke('setup:export', payload),
  openSetupFile: () => invoke('setup:open'),
  applySetup: (payload) => invoke('setup:apply', payload),
  importProductRegistry: (payload) => invoke('studio:importProductRegistry', payload),
  estimateResearchProgram: (payload) => invoke('studio:estimateResearchProgram', payload),
  setThemeStatus: (payload) => invoke('studio:setThemeStatus', payload),

  listWorkbooks: () => invoke('workbooks:list'),
  readWorkbook: (payload) => invoke('workbooks:read', payload),
  importWorkbook: (payload) => invoke('workbooks:import', payload),
  pullGoogleSheet: (payload) => invoke('workbooks:pull-google', payload),
  saveWorkbookEdits: (payload) => invoke('workbooks:save-edits', payload),
  removeWorkbook: (payload) => invoke('workbooks:remove', payload),
  renameWorkbook: (payload) => invoke('workbooks:rename', payload),
  exportWorkbookXlsx: (payload) => invoke('workbooks:export-xlsx', payload),
  exportWorkbookToGoogle: (payload) => invoke('workbooks:export-google', payload),

  saveBrandProfile: (payload) => invoke('save-brand-profile', payload),
  selectBrandProfile: (payload) => invoke('select-brand-profile', payload),
  deleteBrandProfile: (payload) => invoke('delete-brand-profile', payload),
  pickImportFile: (payload) => invoke('pick-import-file', payload),
  previewImportDataset: (payload) => invoke('preview-import-dataset', payload),
  importDataset: (payload) => invoke('import-dataset', payload),
  compareDatasets: (payload) => invoke('compare-datasets', payload),
  saveMonitor: (payload) => invoke('save-monitor', payload),
  readResearchReview: (payload) => invoke('read-research-review', payload),
  saveResearchReview: (payload) => invoke('save-research-review', payload),
  exportResearchReview: (payload) => invoke('export-research-review', payload),
  refreshApifyActors: () => invoke('refresh-apify-actors'),
  searchSources: (payload) => invoke('search-sources', payload),
  previewSearchSources: (payload) => invoke('preview-search-sources', payload),
  askFindings: (payload) => invoke('ask-findings', payload),
  checkAi: (payload) => invoke('check-ai', payload),
  openSourceUrl: (url) => invoke('open-source-url', url),
  appMeta: () => invoke('app-meta'),
  state: () => invoke('state'),
  listMissions: () => invoke('list-missions'),
  saveMission: (payload) => invoke('save-mission', payload),
  runMission: (missionId) => invoke('run-mission', missionId),
  runActionGraph: (payload) => invoke('run-action-graph', payload),
  pauseMission: (missionId) => invoke('pause-mission', missionId),
  scheduleMission: (payload) => invoke('schedule-mission', payload),
  discoverApifyResource: (payload) => invoke('discover-apify-resource', payload),
  testRecipe: (payload) => invoke('test-recipe', payload),
  saveRecipeVersion: (payload) => invoke('save-recipe-version', payload),
  getJob: (jobId) => invoke('get-job', jobId),
  retryJob: (jobId) => invoke('retry-job', jobId),
  readJobLog: (jobId) => invoke('read-job-log', jobId),
  searchEvidence: (payload) => invoke('search-evidence', payload),
  readEvidence: (evidenceId) => invoke('read-evidence', evidenceId),
  exportMissionBundle: (missionId) => invoke('export-mission-bundle', missionId),
  exportAssetPack: (payload) => invoke('export-asset-pack', payload),
  checkCodex: () => invoke('check-codex'),
  testImageProvider: () => invoke('test-image-provider'),
  planIntent: (payload) => invoke('plan-intent', payload),
  runIntent: (payload) => invoke('run-intent', payload),
  runIntentAction: (payload) => invoke('run-intent-action', payload),
  saveKey: (keyName, value) => invoke('save-key', { keyName, value }),
  clearKey: (keyName) => invoke('clear-key', keyName),
  saveSettings: (settings) => invoke('save-settings', settings),
  saveCard: (card) => invoke('save-card', card),
  moveCard: (payload) => invoke('move-card', payload),
  saveAsset: (asset) => invoke('save-asset', asset),
  saveRecipe: (recipe) => invoke('save-recipe', recipe),
  deleteRecipe: (recipeId) => invoke('delete-recipe', recipeId),
  runRecipe: (recipeId) => invoke('run-recipe', recipeId),
  readDataset: (datasetId) => invoke('read-dataset', datasetId),
  exportDataset: (payload) => invoke('export-dataset', payload),
  testSheetsBridge: () => invoke('test-sheets-bridge'),
  saveMondayBoard: (payload) => invoke('save-monday-board', payload),
  clearMondayBoard: () => invoke('clear-monday-board'),
  syncTrendBoardToMonday: (payload) => invoke('sync-trend-board-to-monday', payload),
  archiveAndClearSheets: (payload) => invoke('archive-and-clear-sheets', payload),
  importWorkingSheets: () => invoke('import-working-sheets'),
  exportDatasetToSheets: (payload) => invoke('export-dataset-to-sheets', payload),
  replaySheetRun: (sheetRunId) => invoke('replay-sheet-run', sheetRunId),
  readAnalysis: (analysisId) => invoke('read-analysis', analysisId),
  analyzeDataset: (payload) => invoke('analyze-dataset', payload),
  openAnalysisOutput: (analysisId) => invoke('open-analysis-output', analysisId),
  revealAnalysisOutput: (analysisId) => invoke('reveal-analysis-output', analysisId),
  generateAssets: (payload) => invoke('generate-assets', payload),
  openDataFolder: () => invoke('open-data-folder'),
  openAssetsFolder: () => invoke('open-assets-folder'),
  openAsset: (assetId) => invoke('open-asset', assetId),
  revealAsset: (assetId) => invoke('reveal-asset', assetId),
  openWorkspace: (projectId) => invoke('open-workspace', projectId),
  cancelJob: (jobId) => invoke('cancel-job', jobId),
  onStateChanged: (callback) => {
    const listener = (_, payload) => callback(payload);
    ipcRenderer.on('state-changed', listener);
    return () => ipcRenderer.removeListener('state-changed', listener);
  },
});
